// File created: 2011-08-06 16:28:34

#ifndef MUSHSPACE_TYPENAMES_H
#define MUSHSPACE_TYPENAMES_H

#if MUSHSPACE_93
#define MUSHSPACE_STRUCT_SUFFIX _93
#else
#define MUSHSPACE_STRUCT_SUFFIX
#endif

#define MUSHSPACE_CATHELPER(a,b) a##b
#define MUSHSPACE_CAT(a,b)  MUSHSPACE_CATHELPER(a,b)
#define MUSHSPACE_NAME(x)   MUSHSPACE_CAT(MUSHSPACE_CAT(x,MUSHSPACE_DIM),\
                                          MUSHSPACE_STRUCT_SUFFIX)

#endif
